### ISSUE TITLE
Server sorting makes tools sort worst tool first

### ISSUE THREAD

**Issue by trobb20** [Inventory-Tweaks/inventory-tweaks#73] opened 2013-07-17 14:43 UTC
When i sort my inventory on a server my stone pick replaces my diamond one instead of vice versa, on Singleplayer my diamond one sorts first
![2013-07-17_09 45 01](https://f.cloud.github.com/assets/4975189/812422/89157f74-eeef-11e2-9add-6941628e131c.png)

**Comment by Kobata** [comment] 2013-07-17 20:43
Probably a duplicate of #69

**Comment by brunocee** [comment] 2013-07-23 20:14
Same !

**Closed as completed** 2013-08-03 03:05 UTC
Labels: duplicate
