### ISSUE TITLE
Multiplayer: Doesn't Work

### ISSUE THREAD

**Issue by Distinction** [Inventory-Tweaks/inventory-tweaks#12] opened 2013-03-10 16:55 UTC
Whenever I try to sort items, I end up with a random stack in my hand.

**Comment by shadowz15** [comment] 2013-03-10 17:46
I can't reproduce on a vanilla server, do you have any other mods installed?

**Comment by Distinction** [comment] 2013-03-10 17:51
It only happends on a bukkit server I use to play on, but I can't get ahold of their plugins. It actually happens all servers I join

**Comment by shadowz15** [comment] 2013-03-10 17:52
You using version 1.51b right now correct?

**Comment by Distinction** [comment] 2013-03-10 18:12
1.4.7
Actually, but this has happened before.

**Comment by shadowz15** [comment] 2013-03-10 18:18
Wll Kobata has taken over for MC1.5+, so if your experiencing bugs before this, then they probably wont be fixed, although it would be nice to know what is actually happening. It might plugins with bukkit, it might not. Do some testing with the 1.5pre-release and InvTweaks 1.51b and see if you can reproduce any bugs/glitches, if you have time. Or don't, it doesn't matter-just want the mod kinda bug free before the full-release. I know people don't like downloading a million versions.

**Comment by Distinction** [comment] 2013-03-10 18:30
Well, Can I use 1.51b for MC1.4.7?

**Comment by Kobata** [comment] 2013-03-10 18:31
Usually getting items stuck in your hand means your client isn't correctly synchronized with the server as to what those items are. It usually happens with specific mod items (Especially ones that contain inventories, like forestry backpacks, RP2 canvas bags, etc.)

There are some bukkit plugins that can interfere with sorting, but those usually have your inventory reverting to its state before the sort attempt, not random items showing up.

Issue #6 will fix this for any server that installs the module, but in general it's not something that can be easily fixed in the mod from only the client side.

**Comment by shadowz15** [comment] 2013-03-10 18:34
@Distinction no, 1.51b is only for MC1.5

**Comment by Distinction** [comment] 2013-03-10 18:52
@Kobata This is plainly what happeneds http://www.youtube.com/watch?v=c8Ula1woIG0&feature=youtu.be

**Comment by Kobata** [comment] 2013-03-10 18:58
It looks like they have a plugin that doesn't like how fast sorting happens, but it also doesn't fully revert your inventory so you end up left with the first few movements done and then one partially completed [the item on your cursor].

This would be a plugin/config issue with the server(s) in question.

**Closed as completed by Kobata** 2013-03-10 18:58 UTC
Labels: invalid

**Comment by Distinction** [comment] 2013-03-10 19:00
What can I recommend the server's owner to do?

**Comment by Kobata** [comment] 2013-03-10 19:04
Since I'm not familiar with every possible plugin, I'll quote what the help screen about this says:

If your server seems to 'cancel' what this mod does, it's probably caused by it using the NoCheatPlus plugin.
Ask your admin to disable the following options: "inventory.fastclick" and "combined.improbable"
