### ISSUE TITLE
Sorting an inventory with a Forestry bees causes a crash.

### ISSUE THREAD

**Issue by Prezombie** [Inventory-Tweaks/inventory-tweaks#131] opened 2014-01-26 03:36 UTC
When Forestry is installed you can get bees with hidden data. try and sort a chest with them in it, and you get a massive infinite loop which crashes the server, and the only error message is a huge pile of 

2014-01-25 16:14:27 [WARNING] [Minecraft-Server] Memory connection overburdened; after processing 2500 packets, we still have 11354328 to go!

That number rises every second, until RAM runs out and the server dies.

**Comment by Kobata** [comment] 2014-01-26 04:13
This is not a crash (just things getting slow), and is probably a duplicate of #103.

**Closed as completed by Kobata** 2014-01-26 04:13 UTC
Labels: duplicate
