### ISSUE TITLE
Crash on auto-refill with TConstruct Pickaxe

### ISSUE THREAD

**Issue by eternalcode0** [Inventory-Tweaks/inventory-tweaks#298] opened 2015-11-05 16:49 UTC
**MC Version:** 1.7.10
**Forge Version:** 10.13.4.1541
**InvTweaks Version:** 1.59-dev-152-cf6e263

[Crash Report](http://pastebin.com/VkmkP8sJ)
Minecraft crashed when InvTweaks attempted to auto-refill my Tinkers' Construct pickaxe.
I'm only assuming this is the cause of the crash based of the report.

_Possibly Irrelevant Information_
The exact moment it crashed was when I broke an EnviroMine Coal Ore block with the TConstruct Pickaxe (Wood handle, wood binding, flint pickaxe head). I can provide more details if it's needed.

**Comment by Robijnvogel** [comment] 2016-02-08 08:04
This seems to have been already[ fixed in the code](https://github.com/Inventory-Tweaks/inventory-tweaks/commit/e32ef234e11b18e57cf0c170d3482aaa8640cf06), however the fix has never been released.
At least, I am only assuming you have the same crash as I did, because your pastebin has expired, but I had the same thing (possibly full inventory, TiC pick breaking a block, possible breaking of the pickaxe).

Even the InvTweaks version that you (and I) are using can not be downloaded from the official site.
[This](http://build.technicpack.net/job/Inventory-Tweaks/) is the latest Jenkins build, which I tested a few months ago, but then crashed my client. I will test it again right now.

EDIT:
Yup, getting a "java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin" when trying to start Minecraft with the forelast Forge version, which is newer than that InvTweaks build.

EDIT2:
My bad, that "latest" Jenkins Invtweaks build is for Minecraft 1.8. If you use a build between 153 and 156, you should be fine.

**Comment by eternalcode0** [comment] 2016-02-08 20:24
Well I encountered this crash several months ago so all the versions are out of date at this point and I'm no longer using them anyway. I can't confirm whether this has been fixed in the latest versions at the moment because the computer I'm on now doesn't even have Minecraft on it and I would prefer it stay that way (I use it for personal work only), on top of that I haven't been very active in Minecraft either. Nonetheless, I'll be sure to report any more information on this crash or any others should I find it.

**Comment by Kobata** [comment] 2016-02-08 21:57
The technic jenkins project got disabled when I switched to using java 8, since they don't have that installed there. Newer versions are on the curseforge page.

**Closed as completed by Kobata** 2016-02-08 21:57 UTC

**Comment by Robijnvogel** [comment] 2016-02-09 09:36
Actually, no they aren't. The only MC 1.7.10 version on the CurseForge page is the build eternalcode0 and I were using (152). The Jenkins is disabled indeed, but you can still download the files from there and this particular issue seems to have been solved in build 153. 157 seems to be the first MC 1.8 build, making 156 the latest MC 1.7.10 build. I have confirmed that build 156 works and fixes this issue, so I wonder why you aren't publishing it at CurseForge

**Comment by Robijnvogel** [comment] 2016-02-10 16:52
As I am probably not going to get a response on this, I will create a new issue for this.
